### ISSUE TITLE
FluidStack errors related to pipes with latest Create patch

### ISSUE THREAD

**Issue by HaXrDEV** [thexaero/open-parties-and-claims#446] opened 2024-04-08 17:05 UTC
Everytime a pipe is placed or loaded it will crash/cause an error message (using _Neruina_ here so it doesn't actually crash the game)
[java.lang.RuntimeExceptionMixin transformation of com.simibubi.create.content.fluids.OpenEndedPipe failed](https://gist.github.com/HaXrBOT/ccd35c192936c0345b962a9f91291267)

Removing _Create Support for Open Parties and Claims_ fixes the issue.

Fabric: 0.15.7
Minecraft: 1.20.1
Create Fabric: create-fabric-0.5.1-f-build.1417+mc1.20.1
Create Support for Open Parties and Claims: 1.5.0
Open Parties and Claims: b0.22.0
Other mods: https://gist.github.com/HaXrBOT/cbfb9d1e947d377d0532f7b7b76c7723

**Comment by thexaero** [comment] 2024-04-08 19:26
It's caused by one of their latest updates. You can use an older version of Create until it's fixed.

**Comment by HaXrDEV** [comment] 2024-04-09 15:41
> It's caused by one of their latest updates. You can use an older version of Create until it's fixed.

Reverting to the prior version of _Create Fabric_ (build.1335) doesn't resolve the issue. And i am not comfortable with going back further than that. 
Reverting _OPAC_ to v0.20.4 and _OPAC Create Support_ to v1.3.0 seems to do the trick though.

**Comment by thexaero** [comment] 2024-04-10 11:05
Fixed in 1.6.0 of the Create support extension.

**Closed as completed by thexaero** 2024-04-10 11:05 UTC
Labels: bug, compatibility
