### ISSUE TITLE
last version 1.18.2 Server crash

### ISSUE THREAD

**Issue by DonorKrovi** [thexaero/open-parties-and-claims#119] opened 2022-10-09 12:06 UTC
https://pastebin.com/4JEYdwnf
I don't know why this is happening.

**Comment by thexaero** [comment] 2022-10-09 12:52
Very strange. Do you have "fake players" that actually show up in the player list?
Does it happen a lot?

**Comment by DonorKrovi** [comment] 2022-10-09 15:21
> 

This happened 1 time, is it possible to take into account create and its installation for a fake player?
I have 1 NPC which stands on spawn and opens the menu to players, but it's been there for over a week now

**Comment by thexaero** [comment] 2022-10-09 15:48
Fake players should be fine. It's just strange that it seems like there's supposedly an "actual" player that wasn't handled properly on log in. Can you check the log where this crash is from? Maybe there is an earlier error there.

**Comment by XionioXMaster** [comment] 2022-10-13 10:23
Same

Time: 13.10.2022, 12:20
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "xaero.pac.common.server.task.IServerSpreadoutTask.shouldWork(xaero.pac.common.server.IServerData, Object)" because "task" is null
	at xaero.pac.common.server.core.ServerCore.onServerTickStart(ServerCore.java:79) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	at xaero.pac.common.event.CommonEvents.onServerTick(CommonEvents.java:158) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	at xaero.pac.common.event.CommonEventsForge.onServerTick(CommonEventsForge.java:104) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_59_CommonEventsForge_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%234!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%234!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%234!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactoryMixin.java:937) ~[forge-1.18.2-40.1.80-universal.jar%23178!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:ForgeEventFactoryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:840) ~[server-1.18.2-20220404.173914-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23173!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:fastload.mixins.json:MinecraftServerMixin,pl:mixin:APP:tetrapak.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin}
Caused by: java.lang.NullPointerException: Cannot invoke "xaero.pac.common.server.task.IServerSpreadoutTask.shouldWork(xaero.pac.common.server.IServerData, Object)" because "task" is null
	at xaero.pac.common.server.task.ServerSpreadoutTaskHandler.onTick(ServerSpreadoutTaskHandler.java:65) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	at xaero.pac.common.server.parties.party.sync.PartySynchronizer.lambda$onServerTick$7(PartySynchronizer.java:221) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin,re:mixin}
	at xaero.pac.common.server.parties.party.sync.PartySynchronizer.onServerTick(PartySynchronizer.java:221) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	at xaero.pac.common.server.ServerTickHandler.onTick(ServerTickHandler.java:66) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	at xaero.pac.common.server.core.ServerCore.onServerTickStart(ServerCore.java:77) ~[open-parties-and-claims-forge-1.18.2-0.15.1.jar%23142!/:0.15.1] {re:classloading}
	... 11 more

**Comment by thexaero** [comment] 2022-10-13 11:30
@XionioXMaster Thanks. I think I was right. There is an earlier error unrelated to my mods. It happens while checking if the logged in player is banned. In your case it was the player "Pavel1l". It throws an error and skips the Forge event that handles logged in players. 
If you have an idea what mod is affecting user bans, please let me know.

**Comment by XionioXMaster** [comment] 2022-10-13 13:56
> 

In this case, it is not a mod but a **CMI plugin**

The player reported that he could not log in to the server due to an error
![image](https://user-images.githubusercontent.com/86433158/195616734-d0899558-dc34-4c4d-8bc9-f866620afb75.png)

However after 2 crashes he was able to log in to the server, the error no longer occurred, he played without problems

**Comment by thexaero** [comment] 2022-10-13 15:55
I don't know if this is related but it is certainly something.

**Comment by XionioXMaster** [comment] 2022-10-16 17:26
> I don't know if this is related but it is certainly something.

https://paste.gg/p/anonymous/0def51b8a0584d268b3b2497c1414905

The problem arose again, I went to the server alone (There was no account blocking), the crash occurred when I logged in to the server, I doubt that the matter is in the bans of players

**Comment by XionioXMaster** [comment] 2022-10-16 17:31
Now the crash happens when any player logs on to the server

**Comment by thexaero** [comment] 2022-10-16 23:17
You don't have to be banned for this to be related to player bans. It is related to player bans 100%. That's what the first error is that is thrown in the full log, which is the reason the Forge event isn't fired. Whatever it is, it is not to be fixed on my end. The event is obviously supposed to be fired.

**Comment by thexaero** [comment] 2022-10-16 23:20
Anyway, I'm sure the original report was the same exact issue, so I'm closing this.

**Closed as completed by thexaero** 2022-10-16 23:20 UTC
Labels: bug
